### ISSUE TITLE
Next Symbolic I/O milestone

### ISSUE THREAD

**Issue by travitch** [GaloisInc/crucible#803]
There are a lot of features missing from the symbolic I/O backend. Here are a few that are low-hanging fruit that are important in the near term:

- [ ] Implement errno
- [ ] Implement relative file references, which requires modeling the current working directory
- [ ] Implement file permissions and modes
- [ ] Implement `creat` for creating files
- [ ] Enable `open` to create files (given the appropriate mode)
- [ ] Implement seeking in files (via `lseek`)
- [ ] Implement file status via `stat`
- [ ] Implement symbolic overlays over concrete files
- [ ] Implement constraints in symbolic files (possibly using what4-serialize as the concrete formula syntax)
- [ ] Integrate symio standard output with the override for `printf`
- [ ] Implement a FILE* (C stdio) layer, likely as a set of simple C functions
